name: Github Pages Deploy

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
    types: [closed]

jobs:
  if: github.event.pull_request.merged == true
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x, 16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and build
        run: npm install --save --legacy-peer-deps && npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to
          folder: build # The folder the action should deploy
